modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="my_titan"
version="1.0.0"
displayName="My Titan"
credits="Programming by KillsBoostMyEgo, Models by RetiredTeenager and Jerremy18"
displayURL="https://mcreator.net"
authors="KillsBoostMyEgo, RetiredTeenager, Jerremy18"
description='''
An Attack on Titan mod
'''

[[dependencies.my_titan]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"



[[dependencies.my_titan]]
    modId="just_enough_items"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.my_titan]]
    modId="curios"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.my_titan]]
    modId="patchouli"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.my_titan]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

